backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
detect-transient = true;
detect-client-leader = true;
use-damage = true;
log-level = "warn";

fading = true;
fade-delta = 5;
fade-in-step= 0.1;
fade-out-step= 0.1;

inactive-dim = 0.3;
shadow-exclude = [
    "class_g = 'konsole'"
];

blur:
{
    method = "dual_kawase";
    strength = 7;
}
blur-background-exclude = [
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS@:c"
];

wintypes:
{
    tooltip = { fade = true; shadow = true; opacity = 1; focus = true; full-shadow = false; };
    dock = { shadow = false; };
    dnd = { shadow = false; };
    popup_menu = { opacity = 1; };
    dropdown_menu = { opacity = 1; };
};
