#!/bin/sh
#display status of all git repos

echo -e '\n\e[1;35mDotfiles\e[0m'
cd $HOME/.dotfiles && git status
echo -e '\n\e[1;35mWorkspace\e[0m'
cd $HOME/workspace/sync && git status
echo -e '\n\e[1;35mWallpapers\e[0m'
cd $HOME/Pictures/Wallpapers && git status
